---
- name: "PLAY 1: Leverage ansible-network's network-engine role for parsing"
  hosts: routers
  connection: network_cli
  roles:
    - "ansible-network.network-engine"

  tasks:
    - name: "Get router configuration"
      ios_command:
        commands: "show running-config | section ^vrf_definition"
      register: vrf_config

    - name: "Parse the VRF raw text and return 'vrf_data' dictionary"
      command_parser:
        file: "parsers/vrf.yml"
        content: "{{ vrf_config.stdout[0] }}"

    - name: "SETFACT >> Determine RT import/export differences"
      set_fact:
        needed_vrf_changes: "{{ vrfs | rt_diff(vrf_data) }}"

    - name: "Apply RT state changes"
      ios_config:
        src: "vpn.j2"
        save_when: changed
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result.updates }}"
