---
- hosts: routers
  connection: network_cli
  tasks:
    - ios_config:
        commands:
          - "vrf definition CHEMICAL"
          - "no route-target"
        match: none
        save_when: always
