---
- name: "PLAY 1: Manage VPN config with cli_config and jinja2"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Apply VPN using SSH/CLI"
      cli_config:
        config: "{{ lookup('template', 'templates/vpn.j2') }}"
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: Display relevant changes??"
      listen: config_changed
      debug:
        msg: "{{ cli_result }}"

    - name: "HANDLER 2: Save configuration"
      listen: config_changed
      ios_config:
        save_when: always
