---
- name: "PLAY 1: Manage VPN config with ios_config and jinja2"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Apply VPN using SSH/CLI"
      ios_config:
        src: "templates/vpn.j2"
        save_when: changed
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"
