---
- name: "PLAY 1: Perform SSH/CLI based setup for NETCONF"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Enable NETCONF on routers"
      ios_config:
        commands: "netconf-yang"
        save_when: changed

    - name: "TASK 2: Ensure NETCONF is properly enabled"
      ios_command:
        commands: "show netconf-yang datastores"
        interval: 2
        wait_for:
          - "result[0] contains running"
