---
vrfs:
  - name: "VPN1"
    description: "FIRST VRF"
    rd: "1:1"
    route_import:
      - "100:1"
    route_export:
      - "100:3"
  - name: "VPN2"
    description: "SECOND VRF"
    rd: "2:2"
    route_import:
      - "200:1"
      - "200:2"
    route_export: []
