---
- name: "PLAY 1: Infrastructure-as-code using NETCONF"
  hosts: routers
  connection: netconf
  tasks:
    - name: "TASK 1: Update VRF config with NETCONF"
      netconf_config:
        content: "{{ lookup('template', 'templates/vpn.j2') }}"
