---
- name: "PLAY 1: Infrastructure-as-code using RESTCONF"
  hosts: routers
  connection: local
  tasks:
    - name: "TASK 1: Update VRF config with HTTP PUT"
      uri:
        url: "{{ url }}/Cisco-IOS-XE-native:vrf"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        headers:
          Content-Type: 'application/yang-data+json'
          Accept: >-
            application/yang-data+json,
            application/yang-data.errors+json
        body_format: json
        body: "{{ body }}"
        validate_certs: false
        return_content: true
        status_code:
          - 200
          - 204
      register: rc_result

    - name: "TASK 2: Print status code from HTTP PUT"
      debug:
        msg: "Status: {{ rc_result.status }}"
