---
- name: "PLAY 1: Perform SSH/CLI based setup for RESTCONF"
  hosts: routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Enable RESTCONF on routers"
      ios_config:
        commands: "restconf"
        save_when: changed

- name: "PLAY 2: Perform RESTCONF verification"
  hosts: routers
  connection: local
  tasks:
    - name: "Wait for RESTCONF API to respond via HTTPS"
      uri:
        url: "{{ url }}/Cisco-IOS-XE-native:hostname"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: 'application/yang-data+json'
        validate_certs: false
      register: rc_is_up
      until: "rc_is_up.status == 200"
      retries: 10
      delay: 2
