---
- name: "PLAY 1: Build course lab"
  hosts: routers
  tasks:
    - name: "TASK 1: Apply device configurations using SSH/CLI"
      ios_config:
        src: "configs/{{ inventory_hostname }}.txt"
        save_when: changed
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"

- name: "PLAY 2: Check pings on CSR1"
  hosts: csr1
  tasks:
    - name: "TASK 1: Ping CSR2 Lo1 in POLICE VPN"
      ios_ping:
        dest: 10.0.1.2
        source: Loopback1
        vrf: POLICE

    - name: "TASK 2: Ping CSR2 Lo2 in CHEMICAL VPN"
      ios_ping:
        dest: 10.0.2.2
        source: Loopback2
        vrf: CHEMICAL

    - name: "TASK 3: Ping CSR2 Lo3 in CHEM_MGMT VPN"
      ios_ping:
        dest: 10.0.2.2
        source: Loopback3
        vrf: CHEM_MGMT

- name: "PLAY 3: Check pings on CSR2"
  hosts: csr2
  tasks:
    - name: "TASK 1: Ping CSR1 Lo1 in POLICE VPN"
      ios_ping:
        dest: 10.0.1.1
        source: Loopback1
        vrf: POLICE

    - name: "TASK 2: Ping CSR1 Lo2 in CHEMICAL VPN"
      ios_ping:
        dest: 10.0.2.1
        source: Loopback2
        vrf: CHEMICAL

    - name: "TASK 3: Ping CSR1 Lo3 in CHEMICAL VPN"
      ios_ping:
        dest: 10.0.3.1
        source: Loopback2
        vrf: CHEMICAL
